export const opinionData = 
[
    {
        date: '10.07.2021',
        author: 'Admin',
        votes: '28',
        usefulness: '75%',
        value: 'positive',
        text: 'Pozytywna opinia na temat wykładowcy'
    },
    {
        date: '20.03.2022',
        author: 'Adam Abacki',
        votes: '6',
        usefulness: '66%',
        value: 'negative',
        text: 'HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELL' +
        'OHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHEL' +
        'LOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO'
    },
    {
        date: '27.12.2021',
        author: 'Barbara Abacka',
        votes: '25',
        usefulness: '80%',
        value: 'none',
        text: 'HELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELL' +
        'OHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHEL' +
        'LOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLOHELLO'
    }
  ];